name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: "read"

jobs:
  build:
    name: "Build distribution 📦"
    runs-on: "ubuntu-latest"
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0 # Needed to fetch the version from git
          persist-credentials: false

      - name: "Setup Python"
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.x"

      - name: "Install dependencies"
        run: python -m pip install build==0.8.0

      - name: "Build dists"
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) \
          python -m build

      - name: "Generate hashes"
        id: hash
        run: |
          cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT

      - name: "Upload dists"
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error
          retention-days: 5

  publish-to-pypi-and-github:
    name: "Publish to PyPI"
    if: ${{ github.ref_type == 'tag' }}
    needs: ["build"]
    permissions:
      contents: write # Needed for making GitHub releases
      id-token: write # Needed for trusted publishing to PyPI.
    runs-on: "ubuntu-latest"
    environment:
      name: "publish"

    steps:
    - name: "Download dists"
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
      with:
        name: "dist"
        path: "dist/"

    - name: "Upload dists to a new GitHub Release Draft"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        gh release create "$GITHUB_REF_NAME" \
          --repo "$GITHUB_REPOSITORY" \
          --draft \
          --title "$GITHUB_REF_NAME" \
          --notes "" \
          --verify-tag
        gh release upload "$GITHUB_REF_NAME" dist/* --repo "$GITHUB_REPOSITORY"